version: '3'
services:
  traefik:
    env_file:
      - ./secrets.env
    image: traefik:2.1.3
    restart: always
    networks:
      - home
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/letsencrypt:/letsencrypt
      - ./config/dynamic:/dynamic
      - ./config/tls:/tls
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080

networks:
  home:
    external:
      name: home
