--- 
http: 
  routers: 
    http_catchall: 
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
      entryPoints: 
        - web
      middlewares: 
        - https_redirect
    https_catchall: 
      rule: "HostRegexp(`{any:.+}`)"
      service: noop
      tls: &tls
        certResolver: le
        domains: 
          - 
            main: home.alhome.uk
            sans: 
              - "*.home.alhome.uk"
      entryPoints: 
        - websecure
      middlewares:
        - auth
    api:
      rule: "Host(`t.home.alhome.uk`)"
      service: api@internal
      tls: *tls
      entryPoints:
        - websecure
      middlewares:
        - auth
    hass: 
      rule: "Host(`hass.home.alhome.uk`)"
      service: hass
      tls: *tls
      entryPoints: 
        - websecure
    synology: 
      rule: "Host(`nas.home.alhome.uk`)"
      service: synology
      tls: *tls
      entryPoints: 
        - websecure
      middlewares: 
        - auth
  services: 
    noop: 
      loadBalancer: 
        servers: 
          - 
            url: "https://alhome.uk"
    synology: 
      loadBalancer: 
        servers: 
          - 
            url: "http://192.168.0.39:5000"
  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true
    auth:
      basicAuth:
        usersFile: /dynamic/basicAuthUsers
        realm: "Home"
