log:
  level: "DEBUG"

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.home.alhome.uk`)"
    exposedByDefault: false
  file:
    watch: true
    directory: /dynamic

certificatesResolvers:
  le:
    acme:
      email: "antonyoneill@protonmail.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        delayBeforeCheck: 0
        provider: digitalocean
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

